name: aquayar
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  flutter_bloc: ^8.1.3
  country_picker: ^2.0.20
  persistent_bottom_nav_bar: ^5.0.2
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  google_sign_in: ^6.1.4
  bloc: ^8.1.1
  equatable: ^2.0.5
  dio: ^5.1.2
  logger: ^1.3.0
  meta: ^1.9.1
  path_provider: ^2.0.15
  searchbar_animation: ^0.0.4
  shared_preferences: ^2.1.1
  searchfield: ^0.8.3
  simple_gradient_text: ^1.2.4
  otp_text_field: ^1.1.3
  flutter_riverpod: ^2.3.6
  flutter_spinkit: ^5.2.0
  internet_connection_checker: ^1.0.0+1
  geolocator: ^9.0.2
  json_serializable: ^6.7.0
  clay_containers: ^0.3.2
  flutter_polyline_points: ^1.0.0
  rflutter_alert: ^2.0.7
  flutter_switch: ^0.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_maps_flutter: ^2.4.0
  http: ^0.13.6
  build_runner: ^2.4.6
  hive_generator: ^2.0.0
  uuid: ^3.0.7
  hydrated_bloc: ^9.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: neueplak

      fonts:
        - asset: assets/fonts/neueplak-Regular.ttf

  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
